services:
  axonserver:
    image: 'axoniq/axonserver:latest'
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    ports:
      # Axon 콘솔에 접근하기 위한 용도
      - '8024:8024'
      # Axon 서버 grpc 포트
      - '8124:8124'
